### ISSUE TITLE
ModuleNotFoundError: No module named 'bluetooth.linux'

### ISSUE THREAD

**Issue by ppalaga** [smr99/lego-hub-tk#13]
First of all, thanks for your effort to allow programming the Lego Hub on Linux!

This is what happens when I run `python3 run_command.py ls`:

```
$ python3 run_command.py ls
Traceback (most recent call last):
  File "/home/ppalaga/orgs/python/lego-hub-tk/run_command.py", line 17, in <module>
    from comm.HubClient import ConnectionState, HubClient
  File "/home/ppalaga/orgs/python/lego-hub-tk/comm/HubClient.py", line 5, in <module>
    from comm.MultiplexedConnectionMonitor import MultiplexedConnectionMonitor
  File "/home/ppalaga/orgs/python/lego-hub-tk/comm/MultiplexedConnectionMonitor.py", line 2, in <module>
    from comm.BluetoothConnectionMonitor import BluetoothConnectionMonitor
  File "/home/ppalaga/orgs/python/lego-hub-tk/comm/BluetoothConnectionMonitor.py", line 4, in <module>
    import bluetooth
  File "/home/ppalaga/.local/lib/python3.9/site-packages/bluetooth/__init__.py", line 18, in <module>
    from bluetooth.linux import *
ModuleNotFoundError: No module named 'bluetooth.linux'
```

I have installed the prerequisites via `pip3 install -r requirements.txt` before running `run_command.py ls`.
I am quite new to Python and pip, maybe I am missing something basic.

I am on Fedora 34.

**Comment by smr99** [comment]
Hi Peter!

On Tuesday, December 28, 2021 9:56:34 A.M. CST Peter Palaga wrote:

>   File "/home/ppalaga/.local/lib/python3.9/site-packages/bluetooth/
__init__.py",
> line 18, in <module> from bluetooth.linux import *
> ModuleNotFoundError: No module named 'bluetooth.linux'
> ```
> 
> I have installed the prerequisites via `pip3 install -r requirements.txt`
> before running `run_command.py ls`. I am quite new to Python and pip, maybe
> I am missing something basic.

I don't think you are missing anything.  I looked at line 18 in the file 
mentioned above and on my system it does NOT read "from bluetooth.linux import 
*".  My hunch is that you have a different version of the file than I do.  

I have not updated this stuff in months.

My copy of "bluetooth/__init__.py" has a line that reads:

__version__ = 0.41

What version is in your file?

Thanks,
-Steve

**Comment by ppalaga** [comment]
Thanks Steve, that helped! I had pybluez2 0.44. I did the following to make it work:

```
pip uninstall pybluez2
pip install 'pybluez2==0.41'
```
