### ISSUE TITLE
Using monitor.events.console_print prints only ERROR level messages

### ISSUE THREAD

**Issue by Nurech** [smr99/lego-hub-tk#17]
Hello. I am trying to access `print("test")` being called in a function running on HUB. But I can only receive ERROR level messages (probably not coming from something_changed). However when running toolkit tools like hubcontrol.py I see that `"test"` gets printed on INFO level. How to access INFO level from monitor `event console_print` ?

`start_monitoring_on_pc.py`
```python
import time

from data.HubMonitor import HubMonitor
from comm.HubClient import HubClient, ConnectionState

connection = 0


class Main:
    client = HubClient()
    hm = HubMonitor(client)

    def __init__(self):
        self.hm.events.console_print += self._console_print
        self.client.start()

    def _console_print(self, msg):
        print(msg)


Main()


def send_heartbeat_to_backend(connection):
    # TODO
    if connection == 0:
        print('HUB is offline')
    elif connection == 1:
        print('Connection established to HUB')
    elif connection == 2:
        if not Main.hm.execution_status[1]:
            print('Main program started on HUB')
        if Main.hm.execution_status[1]:
            print('Main program running')


def send_cube_map_to_backend(map):
    # TODO
    print(map)


while True:
    send_heartbeat_to_backend(connection)
    time.sleep(1)
    if Main.hm.connection_state == ConnectionState.TELEMETRY:
        if connection == 0:
            connection = 1
        elif connection == 1:
            Main.client.program_execute(1)
            connection = 2
    else:
        print('waiting...')
```
```bat
HUB is offline
Connection established to HUB
Main program started on HUB
Main program started on HUB
Main program running
ERROR:root:unrecognized motion sensor value: 1
// expecting print("test") to print here
```

EDIT: 
I noticed your commit... https://github.com/smr99/lego-hub-tk/commit/d3b86847873fa80deebf993ccd44b4d3d8f9bf40 after re-adding these lines I got it working as intended. Please update the docs that by default, these events do no fire, instead they are being logged to file (which I saw actually) but I could not find the root cause for it. That - or better yet, make it optional to log to console or file or both. 👍

**Comment by smr99** [comment]
I think you program works as intended -- at least in my testing.  The HubMonitor event console_print **does** fire.

I use the following test program on my hub.

```
from util.print_override import spikeprint;print = spikeprint
print('Hi!')
print('Hey Sailor, how are you??')
```

Both lines were output to the console:

> steve@riemann:~/LegoMindstorms/code/lego-hub-tk$ python3 start_monitoring_on_pc.py 
> HUB is offline
> Connection established to HUB
> Main program started on HUB
> Main program running
> Hi!
> 
> Hey Sailor, how are you??
> 
> Main program running
> Main program running
> Main program running

Is it possible that the "ERROR:root:unrecognized ..." line means your program didn't make it to the print line?

**Comment by Nurech** [comment]
Thank you. I am closing this as I resolved the issue. If anyone else has issues logging `events.console_print` the answer should be in my first post.
